--- # ---
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: nestjs-k8s-namespace
#   name: registry-secret
# stringData:
#   .dockerconfigjson: |
#     {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
# type: kubernetes.io/dockerconfigjson
apiVersion: v1
kind: Secret
metadata:
  namespace: nestjs-k8s-namespace
  name: api-gateway-k8s-secret
type: Opaque
stringData:
  KEYCLOAK_DEBUG: "1"
  KEYCLOAK_BASE_URL: http://auth.microservice.local
  KEYCLOAK_REALM: nestjs-auth
  KEYCLOAK_API_GATEWAY_CLIENT_ID: api-gateway
  KEYCLOAK_API_GATEWAY_SECRET: FM557rZlmf9eeBrp45KbXSGsJEd3R1IY
  KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl6hI/kuJHeYXXZlGH20WPlskrebwty+r1ka2g1svWvJPWH7990kCy9bN3448tZ9xX0uyhF6V9ahIMIp4y3rsShBD2QOtUMqPqwgNHW6riDNPhvdHw2z+LsCfQrxf5gKei2r2uhYxUfpYIhR2waXmS8RxuQOpx0l5q1+fK3NvDHA1l4shQ9U9wXyDBrX7f3/DPLFo6yqd/1FZF8jZQdxZek6LE4pVl3f2mBDQgrQza/8lwWKnesS2An78/U3asdZ0xJEftTgchdG5tw6eWztIGE+56SYsELx2oOe7SlNzkbZx4JXBHvxZ9k5O1BlzPXEh+LoQUXD+GXXfjhL1Dea6qQIDAQAB
  KEYCLOAK_USERS_CREDENTIALS_CLIENT_ID: users-credentials
  KEYCLOAK_USERS_CREDENTIALS_SECRET: RxsJOl94fBnZQiuqVUrECdwDE9hPy9If
  DB_VENDOR: mysql
  DB_ADDR: mysql
  DB_DATABASE: api_gateway
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: root
  KAFKA_BROKER_HOST: my-cluster-kafka-bootstrap.kafka.svc.cluster.local
  KAFKA_BROKER_PORT: "9092"
