apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-kubernetes-namespace
  name: minio-service
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-kubernetes-namespace
  name: minio-deployment
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: nestjs-kubernetes-volume
          persistentVolumeClaim:
            claimName: nestjs-kubernetes-volume
      containers:
        - name: minio
          image: minio/minio:RELEASE.2019-10-12T01-39-57Z
          volumeMounts:
            - name: nestjs-kubernetes-volume
              mountPath: /data
              subPath: minio-x.x.x-data
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nestjs-kubernetes-secret
                  key: MINIO_PASSWORD
          ports:
            - containerPort: 9000
          # readinessProbe:
          #   httpGet:
          #     path: /minio/health/ready
          #     port: 9000
          #   initialDelaySeconds: 120
          #   periodSeconds: 20
          # livenessProbe:
          #   httpGet:
          #     path: /minio/health/live
          #     port: 9000
          #   initialDelaySeconds: 120
          #   periodSeconds: 20
