apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-kubernetes-namespace
  name: data-service
spec:
  selector:
    app: data
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-kubernetes-namespace
  name: data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      volumes:
        - name: nestjs-kubernetes-volume
          persistentVolumeClaim:
            claimName: nestjs-kubernetes-volume
      containers:
        - name: data
          image: nginx:alpine
          volumeMounts:
            - name: nestjs-kubernetes-volume
              mountPath: /usr/share/nginx/html
              subPath: minio-x.x.x-data/public
          ports:
            - containerPort: 80