apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-kubernetes-namespace
  name: nestjs-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: nestjs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-kubernetes-namespace
  name: nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      # imagePullSecrets:
      #   - name: registry-secret
      containers:
        - name: nestjs
          image: newerton/api-gateway:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: nestjs-kubernetes-secret
