apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "app.namespace" . }}
  name: keycloak-configmap
data:
  KEYCLOAK_USER: {{ .Values.auth.keycloak.user }}
  KEYCLOAK_PASSWORD: {{ .Values.auth.keycloak.password }}
  KEYCLOAK_IMPORT: {{ .Values.auth.keycloak.importRealmFile }}
  JAVA_OPTS_APPEND: {{ .Values.auth.keycloak.javaOptsAppend }}