apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "app.namespace" . }}
  name: keycloak-realm-import
data:
  nestjs-auth-realm.json: |
{{ $.Files.Get "config/keycloak/nestjs-auth-realm.json" | indent 4 }}
      
