apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "app.namespace" . }}
  name: keycloak
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-db-wait
          image: busybox:1.30.1
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          command:
            [
              "sh",
              "-c",
              "until nc -w3 -z mysql {{ .Values.images.mysql.port }}; do echo waiting for database; sleep 3; done;",
            ]
      containers:
        - name: keycloak
          image: {{ .Values.images.keycloak.image }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.images.keycloak.http.port }}
            - name: https
              containerPort: {{ .Values.images.keycloak.https.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.keycloak.requests.cpu }}
              memory: {{ .Values.resources.keycloak.requests.memory }}
            limits:
              cpu: {{ .Values.resources.keycloak.limits.cpu }}
              memory: {{ .Values.resources.keycloak.limits.memory }}
          envFrom:
            - configMapRef:
                name: keycloak-configmap
            - secretRef:
                name: keycloak-secret
            - secretRef:
                name: keycloak-secret-database
          volumeMounts:
            - name: keycloak-ha-configmap
              mountPath: /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
              subPath: standalone-ha.xml
            - name: keycloak-import-config
              mountPath: /tmp/test-realm-import.json
              subPath: test-realm-import.json
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
            httpGet:
              path: /auth/realms/master
              port: {{ .Values.images.keycloak.http.port }}
      volumes:
        - name: keycloak-ha-configmap
          configMap:
            name: keycloak-ha-configmap
        - name: keycloak-import-config
          configMap:
            name: keycloak-realm-import
            items:
              - key: test-realm-import.json
                path: test-realm-import.json
