apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "app.namespace" . }}
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_DEBUG: {{ toString .Values.auth.keycloak.debug | b64enc | quote }}
  KEYCLOAK_BASE_INTERNAL_URL: {{ .Values.auth.keycloak.internalUrl | b64enc | quote }}
  KEYCLOAK_BASE_EXTERNAL_URL: {{ .Values.auth.keycloak.externalUrl | b64enc | quote }}
  KEYCLOAK_REALM: {{ .Values.auth.keycloak.realm | b64enc | quote }}
  KEYCLOAK_PUBLIC_KEY: {{ .Values.auth.keycloak.publicKey | b64enc | quote }}
  KEYCLOAK_API_GATEWAY_CLIENT_ID: {{ .Values.auth.keycloak.clients.apiGateway.clientId | b64enc | quote }}
  KEYCLOAK_API_GATEWAY_SECRET: {{ .Values.auth.keycloak.clients.apiGateway.clientSecret | b64enc | quote }}
  KEYCLOAK_USERS_CREDENTIALS_CLIENT_ID: {{ .Values.auth.keycloak.clients.usersCredentials.clientId | b64enc | quote }}
  KEYCLOAK_USERS_CREDENTIALS_SECRET: {{ .Values.auth.keycloak.clients.usersCredentials.clientSecret | b64enc | quote }}