apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "app.namespace" . }}
  name: keycloak-secret-database
type: Opaque
data:
  DB_VENDOR: {{ .Values.auth.keycloak.database.vendor | b64enc | quote }}
  DB_ADDR: {{ .Values.auth.keycloak.database.host | b64enc | quote }}
  DB_DATABASE: {{ .Values.auth.keycloak.database.database | b64enc | quote }}
  DB_PORT: {{ toString .Values.auth.keycloak.database.port | b64enc | quote }}
  DB_USER: {{ .Values.auth.keycloak.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.auth.keycloak.database.password | b64enc | quote }}
