apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "app.namespace" . }}
  name: keycloak
  labels: 
    {{- include "app.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.images.keycloak.http.port }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
