# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: nestjs-k8s
#   name: registry-secret
# stringData:
#   .dockerconfigjson: |
#     {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
# type: kubernetes.io/dockerconfigjson
# ---
apiVersion: v1
kind: Secret
metadata:
  namespace: nestjs-k8s
  name: product-engine-secret
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_DATABASE: products
  DB_USER: postgres
  DB_PASSWORD: postgres
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_USERNAME: default
  REDIS_PASSWORD: redis
  KAFKA_BROKER_HOST: my-cluster-kafka-bootstrap.kafka.svc.cluster.local
  KAFKA_BROKER_PORT: "9092"

