---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nestjs-k8s
  name: redis-pvc-volume
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-k8s
  name: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-k8s
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.5-alpine
          ports:
            - containerPort: 6379
          args:
            [
              "--requirepass",
              "$(REDIS_PASSWORD)",
              "--appendonly",
              "yes",
              "--save",
              "900",
              "1",
              "--save",
              "30",
              "2",
            ]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-engine-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-pvc-volume
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 15
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
      volumes:
        - name: redis-pvc-volume
          persistentVolumeClaim:
            claimName: redis-pvc-volume
