apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-k8s
  name: product-engine
spec:
  selector:
    app: product-engine
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-k8s
  name: product-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-engine
  template:
    metadata:
      labels:
        app: product-engine
    spec:
      imagePullSecrets:
        - name: registry-secret
      initContainers:
        - name: init-db-wait
          image: busybox:1.30.1
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "until nc -w3 -z postgres 5432; do echo waiting for database; sleep 3; done;",
            ]
      containers:
        - name: product-engine
          image: newerton/product-engine:latest
          ports:
            - containerPort: 3003
          lifecycle:
            postStart:
              exec:
                command:
                  ["/bin/sh", "-c", "cd /app && npm run typeorm migration:run"]
          envFrom:
            - secretRef:
                name: product-engine-secret
