# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: nestjs-k8s
#   name: registry-secret
# stringData:
#   .dockerconfigjson: |
#     {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
# type: kubernetes.io/dockerconfigjson
# ---
apiVersion: v1
kind: Secret
metadata:
  namespace: nestjs-k8s
  name: keycloak-secret
type: Opaque
stringData:
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: admin
  KEYCLOAK_IMPORT: /tmp/test-realm-import.json
  JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled
  KEYCLOAK_DEBUG: "1"
  KEYCLOAK_BASE_URL: http://auth.microservice.local
  KEYCLOAK_REALM: nestjs-auth
  KEYCLOAK_API_GATEWAY_CLIENT_ID: api-gateway
  KEYCLOAK_API_GATEWAY_SECRET: FM557rZlmf9eeBrp45KbXSGsJEd3R1IY
  KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAodiSakr2zaw8BWGySM/yUagGhwXj0uk0RNKO5OUbIOnYOiZBFNfd5mQ88ejVIxrxC42pS/tO553rEMi61tZi0rGWF/tb6zF8KN8UVK2axJfDhRDuet+hVP/AUNfQ9SOlSxs8jw0h5fSfpzI5dUKB8lk/xCpHvbMD8ozosvG4TOSlx48Dz07YChShHiuVhgyX58YefU/5HX5P3qzXmDQTnlph3sIjy1EFKfDRGDQjeZ50OrP9xwkqD7os0eoWMqOOQnUpi06stLuTLPdIX81qXKMiJVr9Itjm7gfVMkoMW7ZyaHsgZQjsS/0cqxNWp0oapuxDU/GVfRRw/fmIwxzwUwIDAQAB
  KEYCLOAK_USERS_CREDENTIALS_CLIENT_ID: users-credentials
  KEYCLOAK_USERS_CREDENTIALS_SECRET: RxsJOl94fBnZQiuqVUrECdwDE9hPy9If
  DB_VENDOR: mysql
  DB_ADDR: mysql
  DB_DATABASE: keycloak
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: root
