# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: nestjs-k8s
#   name: registry-secret
# stringData:
#   .dockerconfigjson: |
#     {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
# type: kubernetes.io/dockerconfigjson
# ---
apiVersion: v1
kind: Secret
metadata:
  namespace: nestjs-k8s
  name: keycloak-secret-keys
type: Opaque
stringData:
  KEYCLOAK_DEBUG: "1"
  KEYCLOAK_BASE_INTERNAL_URL: http://keycloak.nestjs-k8s.svc.cluster.local
  KEYCLOAK_BASE_EXTERNAL_URL: http://auth.microservice.local
  KEYCLOAK_REALM: nestjs-auth
  KEYCLOAK_API_GATEWAY_CLIENT_ID: api-gateway
  KEYCLOAK_API_GATEWAY_SECRET: Tm5dXF0OD8MuenulhlrmlliJyMCqrBCj
  KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzjp+lMvAG8ogtSe8EYwRh7nv+8o5/beQ5E0j9uOmJ5WJwg6cw9qm3ZIkvsyPly4mxbx8hz3jtw+N36goZp/uewXXXyCihzNEaj3Vk7WMYS4TTGBjdflzwzGAxz/tiKxwVbniZmbddxm9IwB1RtSnc6B5tA3tG6ix9t0IMHOVnPBN6Dd025rw8vB4iGhHxJVjfnz7y+K1xeTontablPVkFHi1Kbo+OhdcayWTHH3B8xrLSJ5gtcEUMFUHL1iQ4ZdGAZViSvPd6RSpqo6I4FlkEbdPTJVG3QlTUukr6bvJAyruvRv4i6g7J3xz6M1kR7yukrSlxq5Lxc3RDNnZO0S/LwIDAQAB
  KEYCLOAK_USERS_CREDENTIALS_CLIENT_ID: users-credentials
  KEYCLOAK_USERS_CREDENTIALS_SECRET: Bzar2de0jqZKTCzfro1qBgFqmF5Zn6HN