apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "app.namespace" . }}
  name: mysql-secret
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.mysql.password | b64enc | quote }}
