apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "app.namespace" . }}
  name: mysql-initdb-configmap
data:
  initdb.sql: |
    CREATE DATABASE products CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
