apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "app.namespace" . }}
  name: postgresql-initdb
data:
  initdb.sql: |
    CREATE DATABASE keycloak;
    CREATE DATABASE mktplace_products;
    CREATE DATABASE mktplace_orders;
