apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "app.namespace" . }}
  name: {{ .Release.Name }}-kafka-control-center
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      # imagePullSecrets:
      #   - name: registry-secret
      containers:
      - name: {{ .Release.Name }}-kafka-control-center
        image: provectuslabs/kafka-ui:latest
        ports:
          - containerPort: 9000
        env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: "q1Sh-9_ISia_zwGINzRvyQ"
          - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
            value: "mktplace-kafka-controller-0.mktplace-kafka-controller-headless.mktplace-develop.svc.cluster.local:9092"
          - name: KAFKA_CLUSTERS_0_METRICS_PORT
            value: "9997"
          - name: AUTH_TYPE
            value: LOGIN_FORM
          - name: SPRING_SECURITY_USER_NAME
            value: admin
          - name: SPRING_SECURITY_USER_PASSWORD
            value: admin
          - name: SERVER_PORT
            value: '9000'
