apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-kafka-control-center
  labels: 
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 9021
      targetPort: 9021
      nodePort: 30021
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}